---
title: "Lab 1"
author: "Regina Hansson (regha434) and Victor Lells (vicle728)"
date: '2020-09-23'
output: pdf_document
toc: true
toc_depth: 2
---

<!-- {r, echo=FALSE, fig.show="hold", out.width="50%"} -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE)
```

\newpage

## Uppgift 3.1.1 *Likelihoodfunktioner*

### 1)

``` {r}
    llgamma <- function(x, alpha, beta) {
        n <- length(x)
        p1 <- n * (alpha * log(beta)- lgamma(alpha))
        p2 <- (alpha - 1)* sum(log(x))
        p3 <- beta * sum(x)
        p1 + p2  - p3
    } 
```

### 2)
``` {r}
    set.seed(4711)
    x1 <- rgamma(n=10, shape=4, scale=1)
    x2 <- rgamma(n=100, shape=4, scale=1)
    beta <- 0.01
    beta_list <-c()
    results1 <- c()
    results2 <- c()
    
    while (beta <= 3){
        results1 <- c(results1, llgamma(x = x1, alpha = 4, beta = beta))
        results2 <- c(results2, llgamma(x = x2, alpha = 4, beta = beta))
        
        beta_list <- c(beta_list, beta)
        beta <- beta + 0.01
    }
    # Corresponding beta values to the maximal likelihood 
    beta_list[which.max(results1)]
    beta_list[which.max(results2)]
```
    
```{r, echo=FALSE, fig.show="hold", out.width="50%"}
    plot(beta_list, results1, type = "l", main= "Loglikelihood of x1", xlab = "Beta", ylab="log-likelihood")
    plot(beta_list, results2, type = "l", main= "Loglikelihood of x2", xlab = "Beta", ylab="log-likelihood")
```

\newpage

### 3)
``` {r}
    alpha <- 0.01
    alpha_list <-c()
    results1 <- c()
    results2 <- c()
    
    while (alpha <= 10){
        results1 <- c(results1, llgamma(x = x1, alpha = alpha, beta = 1))
        results2 <- c(results2, llgamma(x = x2, alpha = alpha, beta = 1))
        
        alpha_list <- c(alpha_list, alpha)
        alpha <- alpha + 0.01
    }
    # Corresponding alpha values to the maximal likelihood 
    alpha_list[which.max(results1)]
    alpha_list[which.max(results2)]
```
    
```{r, echo=FALSE, fig.show="hold", out.width="50%"}
    plot(alpha_list, results1, type = "l", main= "Loglikelihood of x1", xlab = "Alpha", ylab="log-likelihood")
    plot(alpha_list, results2, type = "l", main= "Loglikelihood of x2", xlab = "Alpha", ylab="log-likelihood")
```

### 4)
% TODO: fraction ^2 (not only mu), root out of log, linebreak

\begin{equation} 
    \ln{L(\mu, \sigma^2)} = ln(\prod_{i=1}^{n} \frac{1}{\sigma*\sqrt{2\pi}} * e^{- 1/2 * \frac{x_i-\mu}{\sigma}^2})
	= n * \ln(\frac{1}{\sigma*\sqrt{2\pi}}) + \sum_{i=1}^{n} - 1/2 * \frac{x_i-\mu}{\sigma}^2 * ln{e}
	= -n * \ln(\sigma*\sqrt{2\pi}) - \frac{1}{2\sigma^2} * \sum_{i=1}^{n} (x_i-\mu)^2
\end{equation}

``` {r}
    llnormal <- function(x, mu, sigma2) {
        n <- length(x)
        p1 <- (n/2) * log(2*pi*sigma2) 
        p2 <- 1/(2*sigma2)
        p3 <- sum((x - mu)**2)
        - p1 - p2 * p3
    } 

	#Test
	llnormal(x1, 2, 1)
```


